#!/usr/bin/env bash

lualatex ttW.tex
for h in *mp; do mpost $h; done
lualatex ttW.tex

lualatex ttZ.tex
for h in *mp; do mpost $h; done
lualatex ttZ.tex

lualatex Zjets.tex
for h in *mp; do mpost $h; done
lualatex Zjets.tex
